### ISSUE TITLE
IMAP Plain-Text

### ISSUE THREAD

**Issue by devkzidane** [antedebaas/DMARC-SMTPTLS-Reports#30]
How can i configure `MAILBOX_CONNECTION` to work with IMAP/143 in plain-text, I'm connecting to local imap server and it's failing because of hostname mismatch (localhost/example.com).

I would like to have it in plain-text since it's local connection anyway.

**Comment by antedebaas** [comment]
As a Security Engineer you should know why never to do so

**Comment by devkzidane** [comment]
It's localhost to localhost connection, if this connection could be intercepted/manipulated there's bigger problems to worry about and SSL wouldn't really be of much help.

**Comment by devkzidane** [comment]
I've looped back a host to 127.0.0.1 to bypass the external connection that's required by ssl (or else i would have to use a self-signed for hostname (localhost)). but i still don't see how could SSL be of any use for localhost to localhost connections?

**Comment by antedebaas** [comment]
Zero trust. ;)

anyway. You can remove the /ssl part in de .env.local file if you don’t use the docker image
But I’m not supporting it

**Comment by devkzidane** [comment]
The only way you could sniff on the loopback interface is with a root process. SSL will only slow you down and cause more problems such as the one i'm facing right now where my dovecot is running with a valid certificate (localhost not in SAN), expiry, etc.

Anyways, I've tried that but it fails for some reason i'm unable to debug with:
`Can't open mailbox {localhost:143\/imap\/}INBOX: invalid remote specification"`

**Comment by antedebaas** [comment]
> But I’m not supporting it

**Comment by devkzidane** [comment]
For anyone with the same needs consider using the URI below in `MAILBOX_CONNECTION`
`localhost:993/imap/ssl/novalidate-cert`

Validating SSL certificates for (localhost) is useless, since they're self-singed and anyone can generate them. Validation will only slow the process down and add zero security and might even add more problems with certificate expiry, etc.

For enhanced security you may use a valid certificate/SAN instead, preferably loop it back to 127.0.0.1 in /etc/hosts. but again if this is a localhost to localhost connection there's no way to intercept on it without root access.
