### ISSUE TITLE
Minor UI Fix - Docker

### ISSUE THREAD

**Issue by tobsowo** [antedebaas/DMARC-SMTPTLS-Reports#7]
I noticed that when viewing the reports the following are missing compared to the screenshot on the README.

DMARC
- There is no record in the Envelope to and from
- No details about the PTR (rDNS)
- Messages count not listed in the single report view

SMTP-TLS
- The domain is not populated on the domain column on dashboard

Domains Page
- The table overviews seem to have the same data for DMARC and SMTP-TLS. Seems the SMTP-TLS is the one not right.

![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/5642737/89ad5a24-b750-412c-ac38-b6f0cd654b56)

![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/5642737/9f6650b2-6492-4666-82dc-6eee1acfdc62)

![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/5642737/2faec391-7b06-4c1f-965e-7f78d0792437)

**Comment by antedebaas** [comment]
Data is filled from the report. If there is no domain there was no domain information in the report. Same goes for the ptr information. It’s not part of the report
