### ISSUE TITLE
First install error

### ISSUE THREAD

**Issue by glardone** [antedebaas/DMARC-SMTPTLS-Reports#72]
Dear all,
I'm trying a new install, but when I launch the command "bash update.sh", when he comes to command 'run migrations', i get this error:

`[critical] Error thrown while running command "doctrine:migrations:migrate --no-interaction --query-time". Message: "An exception occurred in the driver: SQLSTATE[HY000] [14] unable to open database file"

In ExceptionConverter.php line 76:
                                                                                          
  An exception occurred in the driver: SQLSTATE[HY000] [14] unable to open database file  
                                                                                          

In Exception.php line 28:
                                                     
  SQLSTATE[HY000] [14] unable to open database file  
                                                     

In Driver.php line 43:
                                                     
  SQLSTATE[HY000] [14] unable to open database file  
                                                     

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]`

In the .env file I see that it refers to a sqllite database, but is it possible to use mysql instead?
And if so, what parameters are needed to update in the .env file?

Thank you for your support!

Best regards

**Comment by antedebaas** [comment]
it probably tries to find a database where none exist yet.
for the first run you can outcomment the doctrine:migrations:migrate line
just be sure to re-enable it after you have run setup.
please leave this issue open as a reminder for me to fix that in the update.sh

during setup a .env.local file will be created with a database type of your choice

**Comment by antedebaas** [comment]
fixed in 1.9.3

**Comment by jessevallaro** [comment]
This is still an issue for me, just downloaded v1.22.3
