### ISSUE TITLE
Clarification to #7

### ISSUE THREAD

**Issue by tobsowo** [antedebaas/DMARC-SMTPTLS-Reports#9]
The request on #7 are nothing new just that it does not work in the Docker installation and I would have like to share more clarification on them but the issue is locked.

On the SMTP-TLS table, domain is not listed but if you checked individual report you'll see the domain.

When the XML file is uploaded to other DMARC tools, it can show the envelope but it's blank in the Docker installation.

When you visit the domains page with summary of all DMARC and TLS reports, the column for TLS is a repeat of DMARC column.

![IMG_20230928_080341.jpg](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/5642737/47754fff-2896-4cf4-9c02-f2434102435a)

**Comment by antedebaas** [comment]
> The request on #7 are nothing new just that it does not work in the Docker installation and I would have like to share more clarification on them but the issue is locked.
> 
> On the SMTP-TLS table, domain is not listed but if you checked individual report you'll see the domain.
> 
> When the XML file is uploaded to other DMARC tools, it can show the envelope but it's blank in the Docker installation.
> 
is there a domain on the domains page that has an empty namee?

> When you visit the domains page with summary of all DMARC and TLS reports, the column for TLS is a repeat of DMARC column.
that one was already on my list.

**Comment by antedebaas** [comment]
and question 2?

**Comment by tobsowo** [comment]
Not sure I get the policy part but here is a screenshot
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/5642737/2dd04aaf-40e7-4354-9f87-097de6b60c4b)

**Comment by antedebaas** [comment]
its a table in the report view.

i just released v1.1.0 which fixes this

**Comment by antedebaas** [comment]
v1.1.0 also provides the mta-sts.txt file as of now.
if you host it at https://mta-sts.domain.ext/ it will have a generated mta-sts.txt for all known domains at /.well-known/mta-sts.txt

**Comment by tobsowo** [comment]
Thank you.

**Comment by tobsowo** [comment]
I don't want to create a new issue.

Thank you for the latest update with domain editing.

I just updated and noticed that "check maill now" button is not working in my instance.

**Comment by antedebaas** [comment]
This would be a new issue tho :)

A small bug creeped in in the initial 1.1.1 release but was patched right away so I re used the same version number. 
please redownload 1.1.1 from the docker hub and let me know if that fixes it

**Comment by tobsowo** [comment]
Just re-pull and it didn't work yet.

**Comment by antedebaas** [comment]
Fixed a directory rights issue in the image

**Comment by tobsowo** [comment]
It's working now.
Thank you.
